#!/bin/bash
output_file="${$PYFILE}c"
echo "Compiling $PYFILE..."
python3 -m py_compile -b "$PYFILE"
if [ -f "$output_file" ]; then
    echo "Compilation successful."
else
    echo "Compilation failed."
fi
